spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:users
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  security:
    user:
      name: test
      password: test
      roles: CUSTOMER,ADMIN
api:
  security:
    ignored: /api/users/register,/api/banking-app,/api/banking-app/register,/api/banking-app/login,/api/banking-app/users,/swagger-ui/**,/v3/api-docs,/v3/api-docs/**,/index.html,h2-console