spring:
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:users
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  security:
    user:
      name: test
      password: test
      roles: CUSTOMER,ADMIN
jwt:
  secret: '4433rjkl2241@!#23l32j14l3kj12l5j14kl2'
  expiration: 8640000  # Token expiration time in milliseconds (e.g., 24 hours)

api:
  security:
    ignored: /api/users/register,
      /api/users/login,
      /api/admin/login,
      /h2-console,
      /h2-console/**,
      /api/auth/password-reset/verify-otp,
      /api/auth/password-reset/send-otp,
      /api/auth/password-reset,
      /api/users/generate-otp,
      /api/users/verify-otp,
      swagger-ui.html,
      /v3/api-docs/**,
      /swagger-ui/**,
      /actuator/**, /api/admin/accounts