spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: ${DB_PROD_USERNAME}
    password: ${DB_PROD_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


jwt:
  secret: '4433rjkl2241@!#23l32j14l3kj12l5j14kl2'
  expiration: 86400000  # Token expiration time in milliseconds (e.g., 24 hours)

api:
  security:
    ignored: /api/user/register,
      /api/user/login,
      /api/admin/login,
      /h2-console,
      /h2-console/**,
      swagger-ui.html,
      /swagger-ui/**,
      /actuator/**



